apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cash-flow-report
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30000
  type: NodePort