apiVersion: v1
kind: Service
metadata:
  name: cash-flow-report-api-service
  namespace: cash-flow-report
spec:
  selector:
    app: cash-flow-report-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort